import type { Metadata } from "next";
import { JobProvider } from "../app/client/job-control/jobContext";
import localFont from "next/font/local";
import { NextUIProvider } from "@nextui-org/react";
// import { FormProvider } from "./client/job-post/FormContext"; // app dotorh buh child dotor ahiglahaar bol heregley.
import { UserProvider  } from "./context/UserContext";
// import { myTheme } from "../lib/theme";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <UserProvider>
        <JobProvider>
      <body>
        <NextUIProvider >{children}</NextUIProvider>
      </body>
      </JobProvider>
      </UserProvider>
    </html>
  );
}
